name: main
on:
  workflow_dispatch:

jobs:
  docker-build:
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set VERSION To Env
        run: echo "VERSION=$(./gradlew -q getAppName)" >> $GITHUB_ENV
      - name: Set ARCH To Env
        run: echo "ARCH=amd64" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: OS_ARCH=amd64,
          push: true
          tags: stormpx/animed-${{ env.VERSION }}:latest