name: main
on:
  workflow_dispatch:

jobs:
  native-image:
    strategy:
      matrix:
        os: [ubuntu-22.04,ubuntu-22.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.2.2
      
      - name: make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Setup jdk
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'        
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        
      - name: Test Java Ver
        run: java --version
        
      - name: Build Native Image
        run: ./gradlew NativeCompile
        
      - name: Upload executable
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: animed
          path: build/native/nativeCompile/animed
      
    
